let a=5; 
let b=null;
let c="Aashika";
let d;
let f= BigInt("55")+BigInt("4");
let g= Symbol("I am symbol");
let h= true;
console.log(a, b, c , d ,  f ,g ,h);
console.log(typeof g);
console.log(typeof(d));